spring.datasource.url=jdbc:mysql://localhost:3306/elmouden_security?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port = 8090
logging.level.org.springframework.security=DEBUG
# Configuration JWT
jwt.secret=MySuperSecretKeyForJwtAuthentication123456
jwt.expiration=3600000